<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <title>Select Seats</title>
    <link href="../css/seat-selection.css" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-dark text-white">
    <div class="container mt-5">
        <h2>Select Your Seats</h2>
        
        <div class="screen-container">
            <div class="screen">Screen</div>
        </div>
        
        <div class="seat-map" id="seatMap">
            <!-- Seats will be generated by JavaScript -->
        </div>
        
        <div class="mt-4">
            <div class="seat-legend">
                <div class="seat available"></div> Available
                <div class="seat selected"></div> Selected
                <div class="seat occupied"></div> Occupied
            </div>
            
            <div class="booking-summary mt-4">
                <h4>Booking Summary</h4>
                <p>Selected Seats: <span id="selectedSeatsText">None</span></p>
                <p>Total Amount: <span id="totalAmount">0.00</span> LKR</p>
                <button id="proceedToPayment" class="btn btn-primary">Proceed to Payment</button>
            </div>
        </div>
    </div>
    <script>
        const SEAT_PRICE = parseFloat("${ticketPrice}");
        const TICKET_COUNT = parseInt("${sessionScope.ticketCount}");
    </script>
    <script src="../js/seat-selection.js"></script>
</body>
</html>
